### ISSUE TITLE
Improve pipeline documentation

### ISSUE THREAD

**Issue by magdapoppins** [valohai/docs#113]
Could @DrazenDodik and others interested add existing docs painpoints here? What is bad?

**Comment by DrazenDodik** [comment]
- [ ]  [Focuses on the YAML-definition](https://docs.valohai.com/core-concepts/pipelines/), there are no examples of how to run pipelines over APIs and that it's even possible without a yaml file.

- [ ] [Doesn't have an explanation of how node inputs are overridden](https://docs.valohai.com/valohai-yaml/pipeline/) and where do you read the inputs from (apparently not obvious for everyone)

- [ ] [What's the default behavior for node override](https://docs.valohai.com/valohai-yaml/pipeline/nodes/), if the previous step didn't generate an output? 

> The edges/nodes definitions could use more example and can be a bit confusing. For example, on the edges definitions, what is the difference between node/type/key and how do they map to folders. 

> Another small thing we noticed today when running pipelines is about how intermediary folders get passed between nodes. If we set a nodes output to output.predictions*  and the predictions folder itself contains more folders, only the leaf files get passed to the input of the next node. The documentation is not very explicit on this
