### ISSUE TITLE
Update docs for remote debug

### ISSUE THREAD

**Issue by magdapoppins** [valohai/docs#162]

**Comment by DrazenDodik** [comment]
From my point of view, would be great to cover:

- [ ] Prerequisites: Organization admin has enabled SSH access on selected port (guidance on how to do this in Valohai and in your AWS/GCP/Azure)
- [ ] General info: How is access limited/controlled (only available for hybrid and self-hosted environments, each exec has its own ssh key, you can whitelist IPs under your cloud security groups/ firewalls)
- [ ] What kind of limitations do you have (you're in a docker instance, not the whole machine)
- [ ] How to generate an SSH key and add it to a Valohai execution
- [ ] Where can I find the IP of the machine? (Should be on top of the logs when using non-Valohai machines)
- [ ] How to connect from terminal to a Valohai execution
- [ ] How to keep my execution/Docker container up and running so it doesn't interrupt the connection while you're connected inside the container
