### ISSUE TITLE
Document how to do batch predictions

### ISSUE THREAD

**Issue by ruksi** [valohai/docs#45]
Executions can be used to do batch predictions, which is frequently what users want but it might not be obvious that Valohai steps can be used this way.

Add some guide or tutorial about it.

**Comment by akx** [comment]
There's an example here. https://github.com/valohai/tensorflow-example/blob/ec9a35535caf0b814405d4527897451dcbb8e57e/batch_infer.py

**Comment by akx** [comment]
Documented in e.g. https://help.valohai.com/hc/en-us/articles/4419913485329-Batch-inference-on-images
